// packages/svelte/src/components/ThemeModeSwitcher.svelte
<script lang="ts">
  /**
   * ThemeModeSwitcher - Svelte component for theme mode switching
   */
  import { onMount } from 'svelte'
  import { writable, derived } from 'svelte/store'

  export type ThemeMode = 'light' | 'dark' | 'system'

  // Props
  export let defaultMode: ThemeMode = 'system'
  export let storageKey = 'ld-theme-mode'

  // Events
  import { createEventDispatcher } from 'svelte'
  const dispatch = createEventDispatcher<{
    change: ThemeMode
  }>()

  // State
  const currentMode = writable<ThemeMode>(defaultMode)
  const systemPreference = writable<'light' | 'dark'>('light')
  let isOpen = false
  let dropdownRef: HTMLDivElement

  // Mode options
  const modes = [
    { value: 'light' as const, label: '浅色', icon: '☀️' },
    { value: 'dark' as const, label: '深色', icon: '🌙' },
    { value: 'system' as const, label: '跟随系统', icon: '💻' },
  ]

  // Derived values
  const effectiveTheme = derived(
    [currentMode, systemPreference],
    ([$mode, $systemPref]) => ($mode === 'system' ? $systemPref : $mode)
  )

  const currentModeConfig = derived(currentMode, $mode => {
    return modes.find(m => m.value === $mode) || modes[2]
  })

  // Apply theme to DOM
  function applyTheme(theme: 'light' | 'dark') {
    const root = document.documentElement

    if (theme === 'dark') {
      root.setAttribute('theme-mode', 'dark')
    } else {
      root.removeAttribute('theme-mode')
    }

    root.setAttribute('data-theme-mode', theme)
    root.classList.remove('light', 'dark')
    root.classList.add(theme)
  }

  // Update system preference
  function updateSystemPreference() {
    const mediaQuery = window.matchMedia('(prefers-color-scheme: dark)')
    systemPreference.set(mediaQuery.matches ? 'dark' : 'light')
  }

  // Toggle dropdown
  function toggleDropdown() {
    isOpen = !isOpen
  }

  // Change mode
  function changeMode(mode: ThemeMode) {
    currentMode.set(mode)
    localStorage.setItem(storageKey, mode)
    isOpen = false
    dispatch('change', mode)
  }

  // Handle click outside
  function handleClickOutside(event: MouseEvent) {
    if (dropdownRef && !dropdownRef.contains(event.target as Node)) {
      isOpen = false
    }
  }

  onMount(() => {
    // Initialize system preference
    updateSystemPreference()

    // Listen to system theme changes
    const mediaQuery = window.matchMedia('(prefers-color-scheme: dark)')
    const handleChange = () => updateSystemPreference()

    if (mediaQuery.addEventListener) {
      mediaQuery.addEventListener('change', handleChange)
    } else {
      // @ts-ignore - Fallback for older browsers
      mediaQuery.addListener(handleChange)
    }

    // Load saved mode from localStorage
    const savedMode = localStorage.getItem(storageKey) as ThemeMode | null
    if (savedMode && modes.some(m => m.value === savedMode)) {
      currentMode.set(savedMode)
    }

    // Add click outside listener
    document.addEventListener('click', handleClickOutside)

    return () => {
      if (mediaQuery.removeEventListener) {
        mediaQuery.removeEventListener('change', handleChange)
      } else {
        // @ts-ignore - Fallback for older browsers
        mediaQuery.removeListener(handleChange)
      }
      document.removeEventListener('click', handleClickOutside)
    }
  })

  // Apply theme when it changes
  $: applyTheme($effectiveTheme)
</script>

<div class="theme-mode-switcher" bind:this={dropdownRef}>
  <button class="theme-mode-button" on:click={toggleDropdown} title={$currentModeConfig.label}>
    <span class="theme-icon">{$currentModeConfig.icon}</span>
    <span class="theme-label">{$currentModeConfig.label}</span>
    <svg
      class="arrow"
      class:open={isOpen}
      xmlns="http://www.w3.org/2000/svg"
      width="16"
      height="16"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  </button>

  {#if isOpen}
    <div class="theme-dropdown">
      {#each modes as mode}
        {@const isActive = $currentMode === mode.value}
        <button class="theme-option" class:active={isActive} on:click={() => changeMode(mode.value)}>
          <span class="option-icon">{mode.icon}</span>
          <span class="option-label">{mode.label}</span>
          {#if isActive}
            <svg
              class="check-icon"
              xmlns="http://www.w3.org/2000/svg"
              width="16"
              height="16"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
            >
              <path d="M20 6 9 17l-5-5" />
            </svg>
          {/if}
        </button>
      {/each}
    </div>
  {/if}
</div>

<style>
  .theme-mode-switcher {
    position: relative;
    display: inline-block;
  }

  .theme-mode-button {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 8px 12px;
    background: var(--color-bg-container, #ffffff);
    border: 1px solid var(--color-border-light, #e8e8e8);
    border-radius: 8px;
    color: var(--color-text-primary, #000000);
    font-size: 14px;
    font-weight: 500;
    cursor: pointer;
    transition: all 0.3s;
  }

  .theme-mode-button:hover {
    background: var(--color-bg-component-hover, #f5f5f5);
    border-color: var(--color-border, #d9d9d9);
  }

  .theme-icon {
    font-size: 18px;
    line-height: 1;
  }

  .theme-label {
    white-space: nowrap;
  }

  .arrow {
    transition: transform 0.2s ease;
    color: #666;
  }

  .arrow.open {
    transform: rotate(180deg);
  }

  .theme-dropdown {
    position: absolute;
    top: 100%;
    right: 0;
    margin-top: 8px;
    background: var(--color-bg-container, #ffffff);
    border: 1px solid var(--color-border-lighter, #e8e8e8);
    border-radius: 8px;
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
    overflow: hidden;
    z-index: 1000;
    min-width: 160px;
    padding: 4px;
  }

  .theme-option {
    display: flex;
    align-items: center;
    gap: 8px;
    width: 100%;
    padding: 10px 16px;
    background: none;
    border: none;
    border-radius: 6px;
    color: var(--color-text-primary, #000000);
    font-size: 14px;
    cursor: pointer;
    transition: background 0.2s;
    text-align: left;
  }

  .theme-option:hover {
    background: var(--color-bg-component-hover, #f5f5f5);
  }

  .theme-option.active {
    background: var(--color-primary-lighter, #e6f7ff);
    color: var(--color-primary-default, #1890ff);
    font-weight: 600;
  }

  .option-icon {
    font-size: 18px;
    line-height: 1;
  }

  .option-label {
    flex: 1;
  }

  .check-icon {
    color: var(--color-primary-default, #1890ff);
  }

  /* Dark mode styles */
  :global([theme-mode='dark']) .theme-mode-button {
    background: var(--color-bg-component, #1f1f1f);
    border-color: var(--color-border, #434343);
    color: var(--color-text-primary, #ffffff);
  }

  :global([theme-mode='dark']) .theme-mode-button:hover {
    background: var(--color-bg-component-hover, #2a2a2a);
  }

  :global([theme-mode='dark']) .theme-dropdown {
    background: var(--color-bg-container, #141414);
    border-color: var(--color-border, #434343);
  }

  :global([theme-mode='dark']) .theme-option {
    color: var(--color-text-primary, #ffffff);
  }

  :global([theme-mode='dark']) .theme-option:hover {
    background: var(--color-bg-component, #1f1f1f);
  }

  :global([theme-mode='dark']) .theme-option.active {
    background: var(--color-primary-light, #002766);
  }
</style>

// packages/vue/src/components/ThemeModeSwitcher.vue
<template>
  <div class="ld-theme-mode-switcher">
    <button class="mode-button" :title="modeTitle" @click="handleToggle">
      <span class="mode-icon">{{ modeIcon }}</span>
      <span class="mode-text">{{ modeText }}</span>
    </button>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useThemeMode } from '../composables/useThemeMode'

// Props
const props = defineProps<{
  translate?: (key: string) => string
  locale?: string | { value: string }
}>()

// 使用主题模式管理
const { mode, effectiveTheme, toggleMode } = useThemeMode()

// 模式图标映射
const modeIcon = computed(() => {
  switch (mode.value) {
    case 'light':
      return '☀️'
    case 'dark':
      return '🌙'
    case 'auto':
      return '💻'
    default:
      return '☀️'
  }
})

// 模式文本映射
/**
 * 计算当前模式的显示文本
 * 支持国际化翻译
 */
const modeText = computed(() => {
  // 关键修复：正确处理 Ref 类型的 locale prop
  // 如果 props.locale 是 Ref，必须在 computed 内部访问 .value 来建立响应式依赖
  let currentLocale: string | undefined

  // 检查是否有 value 属性（Ref 或类 Ref 对象）
  if (props.locale && typeof props.locale === 'object' && 'value' in props.locale) {
    // 直接访问 .value，建立响应式依赖
    currentLocale = (props.locale as { value: string }).value
  }
  else if (typeof props.locale === 'string') {
    // 普通字符串
    currentLocale = props.locale
  }

  const currentMode = mode.value // 确保追踪 mode 的变化

  // 添加 locale 依赖，确保语言切换时重新计算
  if (currentLocale && props.translate) {
    // locale 或 mode 变化时，这个 computed 会重新计算
    return props.translate(`theme.mode.${currentMode}`)
  }

  if (props.translate) {
    return props.translate(`theme.mode.${currentMode}`)
  }

  switch (currentMode) {
    case 'light':
      return 'Light'
    case 'dark':
      return 'Dark'
    case 'auto':
      return 'Auto'
    default:
      return 'Light'
  }
})

/**
 * 模式提示文本
 * 支持国际化翻译
 */
const modeTitle = computed(() => {
  // 正确处理 Ref 类型的 locale prop
  let currentLocale: string | undefined

  // 检查是否有 value 属性（Ref 或类 Ref 对象）
  if (props.locale && typeof props.locale === 'object' && 'value' in props.locale) {
    // 直接访问 .value，建立响应式依赖
    currentLocale = (props.locale as { value: string }).value
  }
  else if (typeof props.locale === 'string') {
    // 普通字符串
    currentLocale = props.locale
  }

  const currentMode = mode.value // 确保追踪 mode 的变化

  // 添加 locale 依赖，确保语言切换时重新计算
  if (currentLocale && props.translate) {
    const modeStr = props.translate(`theme.mode.${currentMode}`)
    return `${props.translate('theme.currentMode')}: ${modeStr}`
  }

  if (props.translate) {
    const modeStr = props.translate(`theme.mode.${currentMode}`)
    return `${props.translate('theme.currentMode')}: ${modeStr}`
  }

  return `Current mode: ${modeText.value}`
})

// 切换模式
const handleToggle = () => {
  toggleMode()
}
</script>

<style scoped>
.ld-theme-mode-switcher {
  display: inline-block;
}

.mode-button {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 8px 14px;
  border: 2px solid #e5e7eb;
  border-radius: 8px;
  background: white;
  cursor: pointer;
  transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
  font-size: 14px;
  font-weight: 500;
  color: #374151;
  box-shadow: 0 1px 2px rgba(0, 0, 0, 0.05);
  position: relative;
  overflow: hidden;
}

.mode-button::before {
  content: '';
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: linear-gradient(135deg, transparent 0%, rgba(59, 130, 246, 0.1) 100%);
  opacity: 0;
  transition: opacity 0.3s;
}

.mode-button:hover {
  border-color: #3b82f6;
  background: #fafafa;
  transform: translateY(-1px);
  box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
}

.mode-button:hover::before {
  opacity: 1;
}

.mode-button:active {
  transform: translateY(0);
  box-shadow: 0 1px 2px rgba(0, 0, 0, 0.05);
}

.mode-icon {
  font-size: 18px;
  line-height: 1;
  transition: transform 0.3s;
  position: relative;
  z-index: 1;
}

.mode-button:hover .mode-icon {
  transform: rotate(20deg) scale(1.1);
}

.mode-text {
  font-size: 14px;
  line-height: 1;
  position: relative;
  z-index: 1;
  min-width: 50px;
  text-align: left;
}

/* 暗黑模式适配 */
:global(.dark) .mode-button {
  background: var(--color-bg-container, #1f1f1f);
  border-color: var(--color-border, #404040);
  color: var(--color-text-primary, #e5e7eb);
}

:global(.dark) .mode-button:hover {
  background: var(--color-bg-container-secondary, #2a2a2a);
  border-color: var(--color-primary-default, #3b82f6);
}

:global(.dark) .mode-button::before {
  background: linear-gradient(135deg, transparent 0%, rgba(59, 130, 246, 0.15) 100%);
}
</style>
