// examples/vue-example.vue
<template>
  <div class="vue-example">
    <h1>🎨 Vue 3 示例</h1>
    
    <!-- 颜色选择器 -->
    <div class="color-input">
      <label>选择主色调：</label>
      <input 
        type="color" 
        v-model="primaryColor"
        class="color-picker"
      />
      <span class="color-value">{{ primaryColor }}</span>
    </div>
    
    <!-- 加载状态 -->
    <div v-if="loading" class="loading">
      正在生成主题...
    </div>
    
    <!-- 错误状态 -->
    <div v-if="error" class="error">
      错误: {{ error }}
    </div>
    
    <!-- 主题展示 -->
    <div v-if="theme && !loading" class="theme-display">
      <h2>生成的主题</h2>
      
      <!-- 语义化颜色 -->
      <div class="semantic-colors">
        <h3>语义化颜色</h3>
        <div class="color-grid">
          <div 
            v-for="(color, name) in theme.semanticColors"
            :key="name"
            class="color-item"
            :style="{ backgroundColor: color }"
            @click="copyColor(color)"
          >
            <span class="color-name">{{ name }}</span>
            <span class="color-hex">{{ color }}</span>
          </div>
        </div>
      </div>
      
      <!-- 色阶展示 -->
      <div class="palettes">
        <h3>色阶展示</h3>
        <div class="mode-switch">
          <button 
            :class="{ active: currentMode === 'light' }"
            @click="currentMode = 'light'"
          >
            明亮模式
          </button>
          <button 
            :class="{ active: currentMode === 'dark' }"
            @click="currentMode = 'dark'"
          >
            暗黑模式
          </button>
        </div>
        
        <div class="palette-grid">
          <div 
            v-for="(colors, name) in currentPalette"
            :key="name"
            class="palette-row"
          >
            <div class="palette-name">{{ name }}</div>
            <div class="palette-colors">
              <div 
                v-for="(color, index) in colors"
                :key="index"
                class="palette-color"
                :style="{ backgroundColor: color }"
                @click="copyColor(color)"
                :title="`${name}-${index + 1}: ${color}`"
              ></div>
            </div>
          </div>
        </div>
      </div>
    </div>
    
    <!-- 性能指标 -->
    <div v-if="theme" class="performance">
      <h3>性能指标</h3>
      <div class="metrics">
        <div class="metric">
          <span>总耗时:</span>
          <span>{{ metrics.totalTime.toFixed(2) }}ms</span>
        </div>
        <div class="metric">
          <span>缓存命中率:</span>
          <span>{{ (metrics.cacheHitRate * 100).toFixed(1) }}%</span>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { useColor } from '../src/vue/useColor'

// 响应式数据
const primaryColor = ref('#1890ff')
const currentMode = ref<'light' | 'dark'>('light')

// 使用颜色生成Hook
const { 
  theme, 
  loading, 
  error, 
  getPerformanceMetrics 
} = useColor(primaryColor, {
  enableCache: true,
  useWebWorker: false
})

// 当前色阶
const currentPalette = computed(() => {
  if (!theme.value) return {}
  return currentMode.value === 'light' 
    ? theme.value.palettes.light 
    : theme.value.palettes.dark
})

// 性能指标
const metrics = computed(() => {
  return getPerformanceMetrics()
})

// 复制颜色到剪贴板
const copyColor = async (color: string) => {
  try {
    await navigator.clipboard.writeText(color)
    console.log(`已复制颜色: ${color}`)
  } catch (err) {
    console.error('复制失败:', err)
  }
}
</script>

<style scoped>
.vue-example {
  max-width: 800px;
  margin: 0 auto;
  padding: 2rem;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}

.color-input {
  display: flex;
  align-items: center;
  gap: 1rem;
  margin-bottom: 2rem;
}

.color-picker {
  width: 50px;
  height: 40px;
  border: none;
  border-radius: 8px;
  cursor: pointer;
}

.color-value {
  font-family: 'Monaco', 'Menlo', monospace;
  font-weight: 500;
}

.loading, .error {
  padding: 1rem;
  border-radius: 8px;
  margin-bottom: 2rem;
}

.loading {
  background-color: #e6f7ff;
  color: #1890ff;
}

.error {
  background-color: #fff2f0;
  color: #f5222d;
}

.color-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
  gap: 1rem;
  margin-bottom: 2rem;
}

.color-item {
  padding: 1rem;
  border-radius: 8px;
  cursor: pointer;
  transition: transform 0.2s;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 0.5rem;
  min-height: 80px;
  justify-content: center;
}

.color-item:hover {
  transform: translateY(-2px);
}

.color-name {
  font-weight: 600;
  color: rgba(255, 255, 255, 0.9);
  text-shadow: 0 1px 2px rgba(0, 0, 0, 0.3);
  text-transform: capitalize;
}

.color-hex {
  font-family: 'Monaco', 'Menlo', monospace;
  font-size: 12px;
  color: rgba(255, 255, 255, 0.7);
  text-shadow: 0 1px 2px rgba(0, 0, 0, 0.3);
}

.mode-switch {
  display: flex;
  gap: 0.5rem;
  margin-bottom: 1rem;
}

.mode-switch button {
  padding: 0.5rem 1rem;
  border: 1px solid #d9d9d9;
  border-radius: 6px;
  background: white;
  cursor: pointer;
  transition: all 0.2s;
}

.mode-switch button.active {
  background: #1890ff;
  color: white;
  border-color: #1890ff;
}

.palette-grid {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.palette-row {
  display: flex;
  align-items: center;
  gap: 1rem;
}

.palette-name {
  width: 80px;
  font-weight: 500;
  text-transform: capitalize;
}

.palette-colors {
  display: flex;
  flex: 1;
  border-radius: 6px;
  overflow: hidden;
  border: 1px solid #d9d9d9;
}

.palette-color {
  flex: 1;
  height: 40px;
  cursor: pointer;
  transition: transform 0.2s;
}

.palette-color:hover {
  transform: scaleY(1.2);
  z-index: 1;
}

.metrics {
  display: flex;
  gap: 2rem;
}

.metric {
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
}

.metric span:first-child {
  font-size: 12px;
  color: #666;
}

.metric span:last-child {
  font-weight: 600;
  color: #1890ff;
}
</style>

// packages/solid/example.tsx
/**
 * @ldesign/color-solid 使用示例
 * 
 * 这个示例展示了如何在 Solid.js 应用中使用颜色主题管理
 */

import { For, Show } from 'solid-js'
import { useTheme, ThemePicker, ThemeModeSwitcher } from './src/index'
import type { Component } from 'solid-js'

const App: Component = () => {
  // 初始化主题管理
  const {
    currentTheme,
    presets,
    isLoading,
    primaryColor,
    themeName,
    isDark,
    applyTheme,
    applyPresetTheme,
  } = useTheme({
    prefix: 'my-app',
    storageKey: 'my-app-theme',
    immediate: true,
  })

  // 应用自定义颜色
  const handleCustomColor = () => {
    applyTheme('#1890ff')
  }

  // 应用预设主题
  const handlePresetTheme = (presetName: string) => {
    applyPresetTheme(presetName)
  }

  // 主题变更回调
  const handleThemeChange = (value: string, preset?: any) => {
    console.log('主题已更改:', value, preset)
  }

  // 模式变更回调
  const handleModeChange = (mode: 'light' | 'dark' | 'system') => {
    console.log('模式已更改:', mode)
  }

  return (
    <div class="app">
      <header>
        <h1>Solid.js 主题管理示例</h1>
        <div class="controls">
          <ThemePicker
            showSearch={true}
            showCustom={true}
            showArrow={true}
            onChange={handleThemeChange}
          />
          <ThemeModeSwitcher
            defaultMode="system"
            onModeChange={handleModeChange}
          />
        </div>
      </header>

      <main>
        <section class="info-panel">
          <h2>当前主题信息</h2>

          <Show when={!isLoading()} fallback={<p class="loading">加载中...</p>}>
            <div class="theme-info">
              <div class="info-item">
                <label>主题名称:</label>
                <span class="value">{themeName() || '自定义'}</span>
              </div>

              <div class="info-item">
                <label>主题色:</label>
                <span
                  class="color-preview"
                  style={{ 'background-color': primaryColor() }}
                >
                  {primaryColor()}
                </span>
              </div>

              <div class="info-item">
                <label>模式:</label>
                <span class="value">{isDark() ? '深色模式' : '浅色模式'}</span>
              </div>
            </div>
          </Show>
        </section>

        <section class="preset-panel">
          <h2>预设主题</h2>
          <div class="preset-grid">
            <For each={presets}>
              {(preset) => (
                <button
                  class="preset-button"
                  classList={{ active: themeName() === preset.name }}
                  onClick={() => handlePresetTheme(preset.name)}
                  style={{ 'border-color': preset.color }}
                >
                  <span
                    class="preset-color"
                    style={{ 'background-color': preset.color }}
                  />
                  <span class="preset-label">{preset.label}</span>
                </button>
              )}
            </For>
          </div>
        </section>

        <section class="demo-panel">
          <h2>主题效果演示</h2>
          <div class="demo-content">
            <button class="primary-button">主要按钮</button>
            <button class="secondary-button">次要按钮</button>
            <input type="text" placeholder="输入框" class="demo-input" />
            <div class="demo-card">
              <h3>卡片标题</h3>
              <p>这是一个使用主题色的卡片组件。</p>
            </div>
          </div>
        </section>
      </main>

      <style>{`
        .app {
          min-height: 100vh;
          background: var(--my-app-bg-color-page, #f5f5f5);
          color: var(--my-app-text-color-primary, #000000);
          transition: background 0.3s, color 0.3s;
        }

        header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          padding: 1.5rem 2rem;
          background: var(--my-app-bg-color-container, #ffffff);
          border-bottom: 1px solid var(--my-app-component-border, #e8e8e8);
          box-shadow: 0 2px 4px rgba(0, 0, 0, 0.05);
        }

        h1 {
          margin: 0;
          font-size: 1.5rem;
          font-weight: 600;
          color: var(--my-app-text-color-primary, #000000);
        }

        .controls {
          display: flex;
          gap: 1rem;
          align-items: center;
        }

        main {
          padding: 2rem;
          max-width: 1200px;
          margin: 0 auto;
        }

        section {
          margin-bottom: 2rem;
          padding: 1.5rem;
          background: var(--my-app-bg-color-container, #ffffff);
          border-radius: 8px;
          box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);
        }

        h2 {
          margin: 0 0 1rem 0;
          font-size: 1.25rem;
          font-weight: 600;
          color: var(--my-app-text-color-primary, #000000);
        }

        .loading {
          color: var(--my-app-text-color-secondary, #666666);
          font-style: italic;
        }

        .theme-info {
          display: flex;
          flex-direction: column;
          gap: 1rem;
        }

        .info-item {
          display: flex;
          align-items: center;
          gap: 1rem;
        }

        .info-item label {
          font-weight: 500;
          color: var(--my-app-text-color-secondary, #666666);
          min-width: 100px;
        }

        .info-item .value {
          color: var(--my-app-text-color-primary, #000000);
        }

        .color-preview {
          display: inline-flex;
          align-items: center;
          padding: 0.5rem 1rem;
          border-radius: 4px;
          color: white;
          font-weight: 500;
          box-shadow: 0 2px 4px rgba(0, 0, 0, 0.15);
        }

        .preset-grid {
          display: grid;
          grid-template-columns: repeat(auto-fill, minmax(120px, 1fr));
          gap: 1rem;
        }

        .preset-button {
          display: flex;
          flex-direction: column;
          align-items: center;
          gap: 0.5rem;
          padding: 1rem;
          background: var(--my-app-bg-color-component, #fafafa);
          border: 2px solid transparent;
          border-radius: 8px;
          cursor: pointer;
          transition: all 0.2s;
        }

        .preset-button:hover {
          background: var(--my-app-bg-color-component-hover, #f0f0f0);
          transform: translateY(-2px);
        }

        .preset-button.active {
          border-color: currentColor;
          box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
        }

        .preset-color {
          width: 48px;
          height: 48px;
          border-radius: 50%;
          box-shadow: 0 2px 8px rgba(0, 0, 0, 0.15);
        }

        .preset-label {
          font-size: 0.875rem;
          color: var(--my-app-text-color-primary, #000000);
        }

        .demo-content {
          display: flex;
          flex-wrap: wrap;
          gap: 1rem;
          align-items: flex-start;
        }

        .primary-button {
          padding: 0.75rem 1.5rem;
          background: var(--my-app-brand-color, #1890ff);
          color: white;
          border: none;
          border-radius: 4px;
          font-size: 1rem;
          font-weight: 500;
          cursor: pointer;
          transition: background 0.3s;
        }

        .primary-button:hover {
          background: var(--my-app-brand-color-hover, #40a9ff);
        }

        .secondary-button {
          padding: 0.75rem 1.5rem;
          background: var(--my-app-bg-color-component, #fafafa);
          color: var(--my-app-text-color-primary, #000000);
          border: 1px solid var(--my-app-component-border, #d9d9d9);
          border-radius: 4px;
          font-size: 1rem;
          font-weight: 500;
          cursor: pointer;
          transition: all 0.3s;
        }

        .secondary-button:hover {
          border-color: var(--my-app-brand-color, #1890ff);
          color: var(--my-app-brand-color, #1890ff);
        }

        .demo-input {
          padding: 0.75rem 1rem;
          background: var(--my-app-bg-color-component, #ffffff);
          border: 1px solid var(--my-app-component-border, #d9d9d9);
          border-radius: 4px;
          font-size: 1rem;
          color: var(--my-app-text-color-primary, #000000);
          transition: border-color 0.3s;
        }

        .demo-input:focus {
          outline: none;
          border-color: var(--my-app-brand-color, #1890ff);
          box-shadow: 0 0 0 2px var(--my-app-brand-color-light, rgba(24, 144, 255, 0.2));
        }

        .demo-card {
          flex: 1;
          min-width: 250px;
          padding: 1.5rem;
          background: var(--my-app-bg-color-component, #fafafa);
          border: 1px solid var(--my-app-component-border, #e8e8e8);
          border-radius: 8px;
        }

        .demo-card h3 {
          margin: 0 0 0.5rem 0;
          color: var(--my-app-brand-color, #1890ff);
          font-size: 1.125rem;
        }

        .demo-card p {
          margin: 0;
          color: var(--my-app-text-color-secondary, #666666);
          line-height: 1.6;
        }

        /* 深色模式适配 */
        [theme-mode='dark'] .app {
          background: var(--my-app-bg-color-page, #000000);
        }
      `}</style>
    </div>
  )
}

export default App
